### ISSUE TITLE
Vectronics API call broken on master branch

### ISSUE THREAD

**Issue by foresthayes** [Huh/collar#51]
@Huh The fetch_vectronics function no longer works on the master branch.

Following the test for fetch_vectronics this is what the output now looks like:
```
all_dat %>% str  chr [1:46] "c_59000427_59000454_59000468_59000483_59000495_59000504_59000514_59000527_59000535_59000550_59000565_59000569_5"\| __truncated__ ...
```

**Comment by Huh** [comment]
Try again, I just pushed the whole thing after some minor changes.  I will test on my end too.

**Comment by Huh** [comment]
How bout those pretty column names, eh? I hope that function continues to work well, cuz it does make nice names so far...fingers crossed

**Comment by foresthayes** [comment]
> Try again, I just pushed the whole thing after some minor changes. I will test on my end too.

Resolved. Thanks!
