### ISSUE TITLE
Error in fetch_ats function

### ISSUE THREAD

**Issue by foresthayes** [Huh/collar#53]
fetch_ats function returns the following error:

> Error: `nm` must be `NULL` or a character vector the same length as `x`

I think this may be related to the rename section (line 80) but I am not positive.

>   out <- httr::content(dat_dwnld$response, type = "text/csv") %>%
>     dplyr::rename_all(list(~ rename_fun))

**Comment by Huh** [comment]
This is now fixed. The error was due to a syntax change on the tidyverse side...

```R
rename_all(list(~ some_fun)) # is now
rename_all(some_fun)
```
