### ISSUE TITLE
SSL Certificate Expired-Vectronics

### ISSUE THREAD

**Issue by thomasgable** [Huh/collar#70]
Have been using the collar package for some time to download Vectronic data with no issue. Tried to download some data this morning and got the message below. What is the solution to this?

Downloading Vectronics collar data...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL certificate problem: certificate has expired
Called from: curl::curl_fetch_memory(url, handle = handle)

**Comment by ericnewkirk** [comment]
Thanks for reporting this - the same thing happened about a year ago. There's nothing we can do in R to fix it, but it usually doesn't take long for Vectronic to take care of it. I just tried an API call on the demo account using https and it worked fine, so maybe they've corrected it already?

[Vectronic API Test Call](https://api.vectronic-wildlife.com/v2/collar/1000001/gps?collarkey=6484B8CA88E2B996421AB903D0B215AFAE285CAAE932F35F448154398398CF33AC40D37D9E37CEEA9DFCBD89353C3CCF8628A4DB4523F2324A83ADA5D091FB396DAC72773ED8CE1571D5C254FABBA0FBDEE2E1883694B8D18148168B205ED5BFA96ACEC30B7B99E045B8AE145B2A83948BAECD54CAB80A7676360B74CD1DEF7DDB50293E36B1C900EA853E19F808F745D85610F68609F233E294FA1C84700A80F1C257E062CAF4B2467E518A010A59E636091BAB905E50ED300BADF9F90440F7B85BBE14DD864BBB2F77A0A50BE5E14623D1B8FB0C2A3069207F4BFBF6CFEBC152F072D27B3CE88F844ED0197A56AF5114DE7B3BA544DB880850507FEB046684)

**Comment by thomasgable** [comment]
Thanks for the quick response! I just tried again and it worked just fine! Vectronic must have taken care of it already! Wonderful!

**Comment by ericnewkirk** [comment]
Great - that was easy!
