### ISSUE TITLE
Error message when installing devtools::install_github("Huh/collar"....)

### ISSUE THREAD

**Issue by eschaeff** [Huh/collar#81]
"Huh/collar" has been working without issue the last year and suddenly it's started giving me an error message that I can't seem to figure out or understand to run my script. Any assistance is appreciated. Thanks!

> library(devtools)
> devtools::install_github("Huh/collar", dependencies = TRUE, force = TRUE) 

Error: Failed to install 'unknown package' from GitHub:
  schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid

**Comment by Huh** [comment]
Ha, this error is everywhere, see #80 for a related yet unrelated example. I think a deep dive into Rcurl or similar may be the only way to tease this out. I will look around a bit this afternoon and see if I can make any progress. Thanks for the example.

It is probably worth noting that I can't reproduce this error on any of the machines in our office. Also, I would tend to suggest the error is actually coming from devtools::install_github and not the collar package. Are you working from inside a government agency? That could be part of the theme here, some windows update, security related or otherwise.

**Comment by Huh** [comment]
@eschaeff could you please provide output of 

```R
devtools::session_info()
```

I am also assuming that you have a github PAT setup and it works as expected for other packages and operations. Does running the following suggest that you can connect to github?

```R
usethis::git_sitrep()
```

**Comment by ericnewkirk** [comment]
@Huh a PAT shouldn't be required for downloading a public repo, but maybe that's the problem? I wonder if devtools is passing the PAT anyway and it's invalid. I agree the output of `session_info()` and `git_sitrep()` would be super helpful.

@eschaeff can you try logging out of github using your browser, then running `devtools::install_github` again?

**Comment by Huh** [comment]
I guess I was thinking you need to authenticate regardless of the action. Not sure though, I probably spend too much time in private repos.

**Comment by eschaeff** [comment]
@Huh yes, I'm working from an agency computer. I actually recently had a proxy problem that IT fixed, so maybe that created this issue with R since I never had this error in the past. If that is the source of this kind of error, do you recommend any steps I can take to correct it? I agree, it seems like that issue is devtools::install_github, not the collar package. I haven't needed the github PAT setup previously to run this script, but I'll look into that too. Thanks!

> devtools::session_info()
─ Session info ─
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Los_Angeles
 date     2022-09-06
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages ─
 package     * version date (UTC) lib source
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.2.1)
 callr         3.7.2   2022-08-22 [1] CRAN (R 4.2.1)
 cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.1)
 crayon        1.5.1   2022-03-26 [1] CRAN (R 4.2.1)
 devtools      2.4.4   2022-07-20 [1] CRAN (R 4.2.1)
 digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.1)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.1)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.1)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.1)
 gitcreds      0.1.1   2020-12-04 [1] CRAN (R 4.2.1)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.1)
 htmltools     0.5.3   2022-07-18 [1] CRAN (R 4.2.1)
 htmlwidgets   1.5.4   2021-09-08 [1] CRAN (R 4.2.1)
 httpuv        1.6.5   2022-01-05 [1] CRAN (R 4.2.1)
 later         1.3.0   2021-08-18 [1] CRAN (R 4.2.1)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.1)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.1)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.2.1)
 mime          0.12    2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.2.1)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.2.1)
 pkgload       1.3.0   2022-06-27 [1] CRAN (R 4.2.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.1)
 processx      3.7.0   2022-07-07 [1] CRAN (R 4.2.1)
 profvis       0.3.7   2020-11-02 [1] CRAN (R 4.2.1)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.2.1)
 ps            1.7.1   2022-06-18 [1] CRAN (R 4.2.1)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.1)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.1)
 Rcpp          1.0.9   2022-07-08 [1] CRAN (R 4.2.1)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.2.1)
 rlang         1.0.4   2022-07-12 [1] CRAN (R 4.2.1)
 rstudioapi    0.14    2022-08-22 [1] CRAN (R 4.2.1)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
 shiny         1.7.2   2022-07-19 [1] CRAN (R 4.2.1)
 stringi       1.7.8   2022-07-11 [1] CRAN (R 4.2.1)
 stringr       1.4.1   2022-08-20 [1] CRAN (R 4.2.1)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.2.1)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.2.1)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.2.1)

 [1] C:/...
 [2] C:/...
